"""
Planning Agent — sinh 3 "golden brief" cho buổi phỏng vấn (thiết kế tách-brief).

Vì sao tách brief thay vì xuất 1 JSON chứa cả 3 brief?
  Gemma gateway (VNG MaaS) rất hay CẮT/treo khi phải trả một JSON DÀI chứa 3 khối
  markdown (escape \\n nhiều, dễ hỏng → "Invalid JSON: EOF"). Đó là nguồn lỗi
  định dạng + timeout chính. Brief vốn LÀ markdown thuần, không cần bọc JSON.

Thiết kế ổn định:
  1. Grounding chạy TRỰC TIẾP (deterministic, không qua LLM): extract_requirements
     → match_skills → search_problem_bank. Rẻ, không tốn round-trip.
  2. Sinh 3 brief bằng 3 lời gọi LLM RIÊNG, mỗi lời trả MARKDOWN THUẦN (không
     response_format, không JSON). Output mỗi lời ngắn → không bị cắt.
  3. Ba lời gọi chạy TUẦN TỰ (từng brief một). Gateway MaaS chỉ phục vụ ~2
     request đồng thời/key — bắn cả 3 song song khiến brief thứ 3 bị bỏ đói
     (~34s) và dễ chạm timeout → plan degraded; tệ hơn khi nhiều link được tạo
     cùng lúc trong production. Chạy nối tiếp đánh đổi một ít wall-clock danh
     nghĩa lấy sự ỔN ĐỊNH: không starvation, không quá tải gateway, không timeout
     dây chuyền.

Mỗi brief được inject thẳng vào prompt của agent hạ nguồn:
  - interview_brief  → Interview Agent (dẫn dắt hội thoại)
  - evaluation_brief → Inspector Agent (chấm điểm)
  - assignment_brief → Code Assignment Agent (CODING or COGNITIVE test)

assignment_brief is a GENERIC brief: it does not produce the concrete task. It
opens with a one-line, machine-readable ASSIGNMENT DIRECTIVE (in English) telling
the Assignment Agent which kind of task to build (coding|cognitive), the mode
(dsa|project) and whether the AI assistant is enabled. The concrete problem /
questions are generated by the Assignment Agent only when the candidate joins.
"""

import asyncio
import json
import logging
import time

from agent_framework import Agent
from agent_framework.openai import OpenAIChatCompletionClient

from app.config import settings
from app.schemas.plan import InterviewPlan, PlanRequest
from app.skills.jd_analysis.scripts.jd_tools import extract_requirements
from app.skills.interview_planning.scripts.planning_tools import (
    match_skills,
    search_problem_bank,
)

logger = logging.getLogger(__name__)

# The 3 briefs now run SEQUENTIALLY within a single request (see run_planning_agent),
# so this semaphore no longer bounds in-request concurrency — it bounds CROSS-request
# concurrency: when several links are created at once, it caps how many planning LLM
# calls hit the gateway together. The MaaS gateway was measured to serve only ~2
# concurrent requests per key (a 3rd is STARVED to ~34s), so keep this at 2 to match
# the gateway's real capacity and never oversubscribe it. Module-level so all
# simultaneous link creations share the cap.
_LLM_CONCURRENCY = asyncio.Semaphore(2)


# ── System prompt cho từng brief (mỗi lời gọi chỉ sinh ĐÚNG một brief) ─────────
_COMMON_RULES = (
    "You did the heavy CV+JD reading already (grounding facts are given). Write a "
    "dense, golden markdown block specific to THIS candidate — the reader should "
    "never need the raw CV. Ground EVERY claim in the candidate's REAL names, "
    "projects, stack and numbers from the grounding — never placeholders, generic "
    "stand-ins or '[Project X]'. Output MARKDOWN ONLY: no preamble, no JSON, no code "
    "fences around the whole thing, no 'Here is...' line. Honor the HR "
    "special_requirements. Keep it dense and concrete — no filler, no repetition, "
    "no restating the JD verbatim. Stay within the length budget stated in your "
    "brief-specific instructions above."
)

_INTERVIEW_BRIEF_SYS = f"""You are an expert technical interview planner. Write ONLY
the `interview_brief` — a self-contained briefing the LIVE, SPOKEN Interview Agent
reads INSTEAD of the CV. It drives a voice interview, so make it directly usable as a
script. Structure it EXACTLY as:

- **Snapshot** — 2-3 sentences: who the candidate is, their TRUE level (judge from the
  CV, not the JD), standout signals and doubts.
- **## Competencies (weighted)** — reproduce the EXACT competencies and weights from the
  COMPETENCIES list in the context (same names, same weights, same order). Add one phrase
  each on why it matters here. Do NOT invent your own set — the Inspector scores against
  this same list, so they must match.
- **## Interview flow** — open with ONE short, warm opener that anchors on the candidate's
  STRONGEST real project (never "tell me about yourself"). Then the topics IN ORDER. Prefix
  each topic's bold label with the competency it assesses, e.g. **[Competency] hook:**. For
  each topic: ONE concrete MAIN question grounded in the candidate's ACTUAL projects or a
  specific skill GAP, plus a short `probe:` note for what depth to dig (the agent improvises
  its own follow-ups live). Front-load the high-weight competencies and cover EVERY
  competency from the list at least once.

Hard constraints — this is SPOKEN, not written:
- Every question must be answerable OUT LOUD in a sentence or two: no "write code", no
  long multi-part setups, no snippets to read aloud. The hands-on coding/test is a
  SEPARATE assignment — do NOT put it here.
- No boilerplate ("tell me about yourself"); tie everything to THIS candidate.
- Length: up to ~350 words.
{_COMMON_RULES}""".strip()

_EVALUATION_BRIEF_SYS = f"""You are an expert hiring evaluator. Write ONLY the
`evaluation_brief` the Inspector Agent uses to SCORE the candidate after the session and
produce a hire recommendation. Structure it EXACTLY as:

- **## Competencies & weights** — reproduce the EXACT competencies and weights from the
  COMPETENCIES list in the context (same names, same weights). The interview probes this
  same list, so scoring MUST line up with what was actually asked. Do NOT invent your own.
  State up front that each competency is scored 1-5 (1 = no evidence, 3 = adequate for this
  level, 5 = expert with concrete proof).
- For EACH competency: one line describing a 5/STRONG answer and one line describing a
  1-2/WEAK answer — concrete and OBSERVABLE (what the candidate says/does), not vague
  adjectives.
- **## Recommendation guide** — base the call on the WEIGHTED average of the 1-5 scores:
  give the rough weighted-score bands for HIRE vs LEAN-HIRE vs NO-HIRE for THIS role and
  level, and name any single competency that is a HARD GATE (must clear regardless of the
  average).
- **## Red flags** — a short list of disqualifying signals (claims a CV-unsupported skill,
  can't justify decisions under follow-up, vague on ownership, etc.).
- Length: up to ~350 words.
{_COMMON_RULES}""".strip()

_ASSIGNMENT_BRIEF_SYS = f"""You are an expert hiring engineer planning the candidate's
ASSESSMENT. Write ONLY the `assignment_brief` — the prose telling the downstream Assignment
Agent WHAT to build. It does NOT contain the final task itself.

The ASSIGNMENT DIRECTIVE (type / mode / ai_assistant / difficulty) is ALREADY DECIDED — it
is given to you as `assignment_hint` in the context, and the machine-readable directive
line is prepended automatically. Do NOT write that directive line yourself, and do NOT
second-guess the type or mode — write the brief for EXACTLY the hinted type and mode:
- type=coding, mode=dsa → a self-contained algorithmic task the candidate solves unaided;
  name the target function/class shape.
- type=coding, mode=project → a small applied build close to the real job (AI assistant on).
- type=cognitive → the role-relevant aptitudes / judgement to cover (no coding).

Then write a dense markdown brief: the domain/context to ground the task in (the JD's
ACTUAL domain and the candidate's REAL stack — not a generic LeetCode puzzle), the specific
skill to probe (favour the grounding's skill_gaps), the expected shape, and what a strong
solution looks like. The suggested bank problem is only a DIFFICULTY reference. Do NOT write
the final problem statement or questions — that is the Assignment Agent's job at interview
time.
Length: up to ~250 words.
{_COMMON_RULES}""".strip()


_LEVELS = {"junior", "mid", "senior", "manager"}
_DOMAINS = {"backend", "frontend", "data", "devops", "ai"}


def _problem_ref(domain: str, level: str) -> tuple[str, str]:
    """Bài bank gần nhất → (title, difficulty) làm tham chiếu độ khó."""
    problems = search_problem_bank(domain, level)
    p = problems[0] if problems else {}
    return p.get("title", "—"), p.get("difficulty", "medium")


def _assignment_from(level: str, difficulty: str, has_tech_skills: bool = True) -> dict:
    """Directive assignment suy ra deterministic (luôn hợp lệ).

    type quyết bằng TÍN HIỆU đáng tin: JD có tech-skill (taxonomy) → role coding;
    không có tech-skill nào → role phi kỹ thuật → cognitive. (Trước đây luôn trả
    coding, sai cho role marketing/sales.) coding: junior→dsa unaided, còn lại→
    project có AI."""
    if not has_tech_skills:
        return {"type": "cognitive", "mode": "n/a",
                "ai_assistant": "disabled", "difficulty": difficulty}
    if level == "junior":
        mode, ai = "dsa", "disabled"
    else:
        mode, ai = "project", "enabled"
    return {"type": "coding", "mode": mode, "ai_assistant": ai, "difficulty": difficulty}


def _sanitize_assignment(a: dict, level: str) -> dict:
    """Giữ directive NHẤT QUÁN sau khi overlay: cognitive→không mode/AI; coding→mode
    hợp lệ (suy từ level nếu thiếu) + ai_assistant khớp mode."""
    if a["type"] == "cognitive":
        a["mode"], a["ai_assistant"] = "n/a", "disabled"
    else:
        if a["mode"] not in ("dsa", "project"):
            a["mode"] = "dsa" if level == "junior" else "project"
        # ai_assistant là HÀM của mode trong thiết kế (dsa solo, project được dùng AI).
        a["ai_assistant"] = "disabled" if a["mode"] == "dsa" else "enabled"
    return a


def _renormalize(comps: list[dict]) -> list[dict]:
    """Đưa weight về số nguyên dương, TỔNG đúng 100. Phần dư nhét vào item nặng
    nhất để không tạo weight âm/0. Rỗng → rỗng."""
    if not comps:
        return []
    total = sum(max(c["weight"], 0) for c in comps) or len(comps)
    out = [
        {"name": c["name"], "weight": max(1, round(max(c["weight"], 0) * 100 / total))}
        for c in comps
    ]
    diff = 100 - sum(c["weight"] for c in out)
    idx = max(range(len(out)), key=lambda i: out[i]["weight"])
    out[idx]["weight"] = max(1, out[idx]["weight"] + diff)
    return out


def _normalize_competencies(comps: list[dict]) -> list[dict]:
    """Chuẩn hoá competency LLM trả: khử trùng tên, cắt tối đa 6, renormalize 100.
    KHÔNG bịa thêm để đủ 3 (thà ít còn hơn invent) — caller fallback nếu rỗng."""
    seen: set[str] = set()
    clean: list[dict] = []
    for c in comps:
        name = c["name"].strip()
        key = name.lower()
        if name and key not in seen:
            seen.add(key)
            clean.append({"name": name, "weight": c["weight"]})
    return _renormalize(clean[:6])


def _competency_skeleton(
    required_skills: list, skill_gaps: list, mandatory_skills: list | None = None
) -> list[dict]:
    """Bộ competency deterministic từ skill (base + fallback). Thay vì chia đều,
    chấm trọng số theo CÔNG THỨC: must-have ×2, skill còn yếu/thiếu (gap) ×1.5 —
    để gap được probe kỹ hơn — rồi renormalize tổng 100. Gaps đứng trước."""
    ordered = skill_gaps + [s for s in required_skills if s not in skill_gaps]
    ordered = ordered[:5] or ["Core role competency"]
    mand = set(mandatory_skills or required_skills)
    gaps = set(skill_gaps)
    raw = []
    for s in ordered:
        w = 1.0
        if s in mand:
            w *= 2.0
        if s in gaps:
            w *= 1.5
        raw.append({"name": s, "weight": w})
    return _renormalize(raw)


def _ground(req: PlanRequest) -> dict:
    """Grounding KEYWORD (deterministic, không gọi LLM) — vừa là base, vừa là
    FALLBACK khi tầng semantic hỏng. Bản thân nó NÔNG (khớp chữ), nên chỉ đóng vai
    lưới an toàn; tầng ``_ground_semantic`` ở trên mới thật sự 'hiểu nghĩa'."""
    reqs = extract_requirements(req.jd_text, req.position or "")
    skills = match_skills(req.cv_markdown, reqs["required_skills"])
    level, domain = reqs["seniority_level"], reqs["domain"]
    title, difficulty = _problem_ref(domain, level)
    return {
        "seniority_level": level,
        "seniority_reason": "keyword heuristic (no CV-depth reasoning)",
        "domain": domain,
        "min_years_experience": reqs["min_years_experience"],
        "required_skills": reqs["required_skills"],
        # Keyword path can't tell must-have apart → treat all required as mandatory.
        "mandatory_skills": reqs["required_skills"],
        "evidenced_skills": skills["matched_skills"],
        # No CV-depth reasoning here → no per-skill proof; semantic layer fills this.
        "skills_evidence": [],
        "skill_gaps": skills["skill_gaps"],
        "competencies": _competency_skeleton(
            reqs["required_skills"], skills["skill_gaps"]
        ),
        "assignment": _assignment_from(
            level, difficulty, has_tech_skills=bool(reqs["required_skills"])
        ),
        "suggested_problem": title,
        "suggested_difficulty": difficulty,
    }


_GROUNDING_SYS = """You are a senior technical recruiter doing pre-interview analysis.
Read the JOB DESCRIPTION and CANDIDATE CV and extract a COMPACT grounding object.
Reason about MEANING, not keywords: infer the candidate's TRUE seniority from the depth,
scope and years actually described (do NOT just trust the JD's label), and judge skills
from evidence even when phrased differently (e.g. "built event-driven pipelines" is
streaming/messaging experience; "owned the on-call rotation" is real ops maturity).

Output ONLY one minified JSON object — no prose, no markdown, no code fence — with
EXACTLY these keys:
{"seniority_level":"junior|mid|senior|manager","seniority_reason":"<=12 words why",
"domain":"backend|frontend|data|devops|ai","required_skills":["what the role needs"],
"mandatory_skills":["the MUST-HAVE subset of required_skills"],
"evidenced_skills":["what the CV truly demonstrates"],
"skills_evidence":[{"name":"skill","years":2,"evidence":"<=12 words quoted from the CV"}],
"skill_gaps":["role needs but CV is weak/absent — these get probed"],
"competencies":[{"name":"...","weight":30}],
"assignment":{"type":"coding|cognitive","mode":"dsa|project|n/a","ai_assistant":"enabled|disabled","difficulty":"easy|medium|hard"}}
Rules: competencies = the 3-6 things MOST worth assessing for THIS hire — BLEND the
must-have strengths to VERIFY with the critical gaps to PROBE; order by priority and weight
by impact on the role (NOT evenly), integer weights summing to ~100.
skills_evidence: ONLY skills the CV truly backs, each with the years shown (omit/0 if
unstated) and a SHORT proof quoted NEAR-VERBATIM from the CV (a real phrase / number /
project name) — never invented or paraphrased into something generic.
Keep every array short and specific. Calibrate difficulty to the TRUE level."""


def _parse_grounding(text: str, base: dict) -> dict:
    """Parse JSON analyst PHÒNG THỦ; overlay field hợp lệ lên ``base``.

    Bất kỳ lỗi nào (JSON hỏng, thiếu/sai field) → field đó GIỮ giá trị keyword base.
    Không bao giờ ném ra → grounding luôn có kết quả dùng được."""
    g = dict(base)
    try:
        s = text.strip()
        i, j = s.find("{"), s.rfind("}")
        if i == -1 or j == -1:
            return g
        data = json.loads(s[i : j + 1])
    except Exception:  # noqa: BLE001
        return g

    if data.get("seniority_level") in _LEVELS:
        g["seniority_level"] = data["seniority_level"]
    reason = data.get("seniority_reason")
    if isinstance(reason, str) and reason.strip():
        g["seniority_reason"] = reason.strip()[:120]
    if data.get("domain") in _DOMAINS:
        g["domain"] = data["domain"]
    for key in ("required_skills", "mandatory_skills", "evidenced_skills", "skill_gaps"):
        val = data.get(key)
        if isinstance(val, list) and all(isinstance(x, str) for x in val):
            g[key] = [x.strip() for x in val if x.strip()]

    # Bằng chứng theo từng skill (name + năm KN + quote ngắn từ CV). Phòng thủ:
    # field sai kiểu bị bỏ; quote bị cắt 140 ký tự để không phình prompt brief.
    ev = data.get("skills_evidence")
    if isinstance(ev, list):
        clean_ev = []
        for e in ev:
            if isinstance(e, dict) and isinstance(e.get("name"), str) and e["name"].strip():
                years = e.get("years")
                proof = e.get("evidence")
                clean_ev.append({
                    # years 0/âm = "không nêu" → None (prompt cho phép omit/0).
                    "name": e["name"].strip(),
                    "years": years if isinstance(years, (int, float)) and years > 0 else None,
                    "evidence": proof.strip()[:140] if isinstance(proof, str) else "",
                })
        g["skills_evidence"] = clean_ev

    comps = data.get("competencies")
    if isinstance(comps, list):
        clean = [
            {"name": c["name"].strip(), "weight": int(c["weight"])}
            for c in comps
            if isinstance(c, dict)
            and isinstance(c.get("name"), str) and c["name"].strip()
            and isinstance(c.get("weight"), (int, float))
        ]
        normalized = _normalize_competencies(clean)
        if normalized:
            g["competencies"] = normalized
    a = data.get("assignment")
    if isinstance(a, dict):
        merged = dict(g["assignment"])
        if a.get("type") in ("coding", "cognitive"):
            proposed = a["type"]
            # JD có tech-skill (tín hiệu keyword đáng tin) → role CODING. Chặn analyst
            # lỡ flip sang cognitive cho role kỹ thuật (đã quan sát lỗi này thực tế).
            if proposed == "cognitive" and base["required_skills"]:
                proposed = "coding"
            merged["type"] = proposed
        if a.get("mode") in ("dsa", "project", "n/a"):
            merged["mode"] = a["mode"]
        if a.get("ai_assistant") in ("enabled", "disabled"):
            merged["ai_assistant"] = a["ai_assistant"]
        if a.get("difficulty") in ("easy", "medium", "hard"):
            merged["difficulty"] = a["difficulty"]
        g["assignment"] = _sanitize_assignment(merged, g["seniority_level"])

    # domain/level có thể đã đổi → làm tươi tham chiếu bài + difficulty hint.
    g["suggested_problem"], g["suggested_difficulty"] = _problem_ref(
        g["domain"], g["seniority_level"]
    )
    return g


async def _ground_semantic(
    client: OpenAIChatCompletionClient, req: PlanRequest, base: dict
) -> dict:
    """Một lời gọi LLM 'analyst' → grounding HIỂU NGHĨA; lỗi/timeout → trả ``base``.

    Bị chặn bởi cùng timeout/semaphore như brief. Output là JSON PHẲNG & NGẮN nên
    ít nguy cơ bị gateway cắt hơn nhiều so với JSON 3-brief (lý do thiết kế cũ bỏ
    JSON là vì khối markdown DÀI, không phải vì JSON nhỏ)."""
    agent = Agent(client, _GROUNDING_SYS, name="PlanningAgent::grounding")
    t0 = time.perf_counter()
    try:
        async with _LLM_CONCURRENCY:
            result = await asyncio.wait_for(
                agent.run(
                    _grounding_context(req),
                    options={
                        "temperature": 0.1,
                        "max_tokens": settings.planning_analyst_max_tokens,
                    },
                ),
                timeout=settings.planning_request_timeout,
            )
        g = _parse_grounding(result.text or "", base)
        logger.info(
            "planning: semantic grounding in %.1fs — level=%s (%s), domain=%s, "
            "%d competencies", time.perf_counter() - t0, g["seniority_level"],
            g["seniority_reason"], g["domain"], len(g["competencies"]),
        )
        return g
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "planning: semantic grounding failed in %.1fs (%s) — keyword base",
            time.perf_counter() - t0, str(exc)[:160],
        )
        return base


def _evidenced_block(facts: dict) -> str:
    """Dòng 'evidenced_in_cv': ưu tiên bằng chứng có cấu trúc (skill + năm + quote)
    để brief bám CHỨNG CỨ thật; rỗng → fallback liệt kê tên skill phẳng."""
    ev = facts.get("skills_evidence") or []
    if ev:
        lines = "\n".join(
            f"  - {e['name']}"
            + (f" (~{e['years']}y)" if e.get("years") else "")
            + (f": {e['evidence']}" if e.get("evidence") else "")
            for e in ev
        )
        return f"evidenced_in_cv (with proof):\n{lines}"
    return f"evidenced_in_cv: {', '.join(facts['evidenced_skills']) or '—'}"


def _facts_block(facts: dict) -> str:
    comps = "\n".join(
        f"{i}. {c['name']} — {c['weight']}%"
        for i, c in enumerate(facts["competencies"], 1)
    ) or "—"
    a = facts["assignment"]
    return (
        "=== GROUNDING (semantic when available, keyword fallback otherwise) ===\n"
        f"seniority_level: {facts['seniority_level']} — {facts['seniority_reason']}\n"
        f"primary_domain: {facts['domain']}\n"
        f"jd_min_years: {facts['min_years_experience']}\n"
        f"required_skills: {', '.join(facts['required_skills']) or '—'}\n"
        f"must_have_skills: {', '.join(facts.get('mandatory_skills') or []) or '—'}\n"
        f"{_evidenced_block(facts)}\n"
        f"skill_gaps (PROBE these): {', '.join(facts['skill_gaps']) or '—'}\n"
        f"assignment_hint: type={a['type']} mode={a['mode']} "
        f"ai_assistant={a['ai_assistant']} difficulty={a['difficulty']}\n"
        f"suggested_coding_problem (difficulty ref): "
        f"{facts['suggested_problem']} ({facts['suggested_difficulty']})\n\n"
        "=== COMPETENCIES (use THESE EXACT names + weights; do NOT invent your own) "
        f"===\n{comps}"
    )


def _grounding_context(req: PlanRequest) -> str:
    """Context thô (POSITION + JD + CV + HR) — dùng cho analyst grounding."""
    return f"""POSITION: {req.position or "Software Engineer"}

=== JOB DESCRIPTION ===
{req.jd_text}

=== CANDIDATE CV (markdown) ===
{req.cv_markdown}

=== SPECIAL REQUIREMENTS FROM HR ===
{req.special_requirements or "None specified."}"""


def _context(req: PlanRequest, facts: dict) -> str:
    """Phần user message dùng chung cho cả 3 brief = context thô + grounding facts."""
    return f"{_grounding_context(req)}\n\n{_facts_block(facts)}"


def _duration_minutes(seniority: str) -> int:
    return {"junior": 45, "mid": 50, "senior": 60, "manager": 60}.get(seniority, 50)


def _assignment_directive(facts: dict) -> str:
    """Directive line máy-đọc cho Assignment Agent (downstream PARSE dòng này).

    Đọc thẳng ``facts['assignment']`` — đã được grounding (semantic hoặc keyword)
    quyết định sẵn, nên luôn hợp lệ kể cả khi brief LLM hỏng."""
    a = facts["assignment"]
    return (
        f"ASSIGNMENT DIRECTIVE → type: {a['type']} · mode: {a['mode']} · "
        f"ai_assistant: {a['ai_assistant']} · difficulty: {a['difficulty']}"
    )


def _ensure_directive(brief: str, facts: dict) -> str:
    """Bảo chứng assignment_brief LUÔN mở đầu bằng directive DETERMINISTIC từ facts.

    Directive (type/mode/ai_assistant/difficulty) do grounding quyết — KHÔNG để brief
    LLM tự viết/tự đoán (đã thấy nó lệch sang 'cognitive' cho role coding). Nếu LLM lỡ
    viết một dòng directive, ta CẮT bỏ rồi thay bằng dòng chuẩn. Idempotent với fallback
    brief (vốn đã có directive)."""
    body = brief.lstrip()
    if body.upper().startswith("ASSIGNMENT DIRECTIVE"):
        parts = body.split("\n", 1)
        body = parts[1].lstrip() if len(parts) > 1 else ""
    return f"{_assignment_directive(facts)}\n\n{body}".rstrip()


def _fallback_brief(label: str, req: PlanRequest, facts: dict) -> str:
    """Brief deterministic dựng TỪ grounding facts khi lời gọi LLM hỏng.

    Plainer than the LLM brief, nhưng tự chứa và dùng được ngay — giúp request
    LUÔN trả 200 (degrade gracefully) thay vì 500 chỉ vì một brief treo/timeout.
    """
    pos = req.position or "Software Engineer"
    level = facts["seniority_level"]
    skills = ", ".join(facts["required_skills"]) or "—"
    gaps = ", ".join(facts["skill_gaps"]) or "—"
    matched = ", ".join(facts["evidenced_skills"]) or "—"
    comps = ", ".join(
        f"{c['name']} ({c['weight']}%)" for c in facts["competencies"]
    ) or "—"
    special = (req.special_requirements or "").strip()
    special_line = f"\n- HR focus: {special}" if special else ""

    if label == "interview_brief":
        return (
            f"## Interview Brief — {pos} ({level})\n"
            f"- Competencies (weighted): {comps}\n"
            f"- Evidenced in CV (probe for depth): {matched}\n"
            f"- **Gaps to dig into**: {gaps}{special_line}\n\n"
            "### How to run it\n"
            "Open on the candidate's actual experience, then probe each gap above "
            "with concrete, scenario-based questions tied to their projects. "
            "Confirm the evidenced skills are real, not keyword-deep. Avoid generic "
            "warm-ups."
        )
    if label == "evaluation_brief":
        return (
            f"## Evaluation Brief — {pos} ({level})\n"
            f"- Score on these competencies (weighted): {comps}\n"
            f"- Pay extra attention to the gaps: {gaps}{special_line}\n\n"
            "### Rubric\n"
            "- **Strong**: explains trade-offs, gives concrete examples, reasons "
            "about edge cases and failure modes.\n"
            "- **Weak**: keyword-level answers, no depth, cannot justify decisions.\n\n"
            "### Red Flags\n"
            "Claims a skill the CV does not support; vague on past project ownership; "
            "no reasoning under follow-up questions."
        )
    # assignment_brief — MUST open with the machine-readable directive line.
    return (
        f"{_assignment_directive(facts)}\n\n"
        f"## Assignment Brief — {pos} ({level})\n"
        f"- Ground the task in this domain: {facts['domain']}.\n"
        f"- Target the candidate's stack / required skills: {skills}.\n"
        f"- Difficulty reference: {facts['suggested_problem']} "
        f"({facts['suggested_difficulty']}).{special_line}\n\n"
        "Build a task that exercises the role's real work — not a generic puzzle. "
        "The Assignment Agent produces the concrete problem at interview time."
    )


async def _gen_brief(
    client: OpenAIChatCompletionClient, system_prompt: str, context: str, label: str
) -> str:
    """Sinh MỘT brief = một lời gọi LLM trả markdown thuần. Retry tối đa 2 lần
    CHỈ khi rỗng/lỗi/timeout (không phải lỗi định dạng JSON — đã bỏ JSON).

    Mỗi attempt bị chặn bởi ``planning_request_timeout`` qua ``asyncio.wait_for``
    để một gateway treo không kéo cả request đợi tới khi backend timeout; giữa
    2 attempt có backoff nhẹ để dịu các lỗi tức thời (429/treo chớp nhoáng)."""
    agent = Agent(client, system_prompt, name=f"PlanningAgent::{label}")
    for attempt in (1, 2):
        # Log the launch time (monotonic): comparing the 3 briefs' start stamps
        # reveals whether the gateway runs them concurrently (~same start) or
        # serializes them (staggered starts).
        t0 = time.perf_counter()
        logger.info(
            "%s: LLM call START (attempt %d) @t=%.3f", label, attempt, time.monotonic()
        )
        try:
            # Cap concurrent gateway calls (see _LLM_CONCURRENCY): the timeout
            # wraps only the actual call, so time spent waiting for a slot does
            # not count against it.
            async with _LLM_CONCURRENCY:
                t_call = time.perf_counter()
                result = await asyncio.wait_for(
                    agent.run(
                        context,
                        options={
                            "temperature": settings.planning_temperature,
                            "max_tokens": settings.planning_max_tokens,
                        },
                    ),
                    timeout=settings.planning_request_timeout,
                )
            elapsed = time.perf_counter() - t0
            queued = t_call - t0
            text = (result.text or "").strip()
            if text:
                # Bỏ code-fence bao ngoài nếu model lỡ bọc cả khối.
                if text.startswith("```"):
                    body = text.split("```")
                    text = body[1] if len(body) > 1 else text
                    if text.lstrip().startswith(("markdown", "md")):
                        text = text.split("\n", 1)[1] if "\n" in text else text
                    text = text.strip().rstrip("`").strip()
                logger.info(
                    "%s: DONE in %.1fs (queued %.1fs + call %.1fs) — %d chars "
                    "(attempt %d)",
                    label, elapsed, queued, elapsed - queued, len(text), attempt,
                )
                return text
            logger.warning(
                "%s: empty brief in %.1fs (attempt %d)", label, elapsed, attempt
            )
        except asyncio.TimeoutError:
            # Don't retry from zero on timeout: at 75s the gateway is stuck, and
            # a fresh attempt just pays the full cost again. Give up this brief
            # (the backend degrades to a mock plan if a brief is missing).
            logger.warning(
                "%s: LLM call TIMED OUT after %.1fs (limit %.0fs) — giving up, "
                "no retry", label, time.perf_counter() - t0,
                settings.planning_request_timeout,
            )
            break
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "%s: gen FAILED in %.1fs (attempt %d): %s",
                label, time.perf_counter() - t0, attempt, str(exc)[:160],
            )
        if attempt < 2:
            await asyncio.sleep(0.5 * attempt)  # backoff nhẹ trước khi retry
    raise ValueError(f"Planning Agent could not generate {label} after retries.")


def _verify_briefs(briefs: dict[str, str], facts: dict) -> list[str]:
    """Check NHẤT QUÁN bằng CODE (0 round-trip): interview_brief & evaluation_brief
    có thật sự nhắc tới bộ competency đã chốt không. Đây là LƯỚI QUAN SÁT — chỉ log
    cảnh báo khi một brief bỏ sót quá nửa competency, KHÔNG sinh lại (giữ tốc độ) và
    KHÔNG đổi nội dung. Trả danh sách brief lệch để caller log."""
    names = [c["name"] for c in facts["competencies"]]
    if not names:
        return []
    inconsistent: list[str] = []
    for label in ("interview_brief", "evaluation_brief"):
        text = (briefs.get(label) or "").lower()
        missing = [n for n in names if n.lower() not in text]
        if len(missing) > len(names) / 2:
            inconsistent.append(label)
            logger.warning(
                "planning: %s drifted from grounding — %d/%d competencies missing: %s",
                label, len(missing), len(names), ", ".join(missing),
            )
    return inconsistent


async def run_planning_agent(req: PlanRequest) -> InterviewPlan:
    """Sinh InterviewPlan: grounding trực tiếp + 3 brief markdown TUẦN TỰ."""
    client = OpenAIChatCompletionClient(
        model=settings.planning_model,
        api_key=settings.openai_api_key or None,
        base_url=settings.openai_base_url or None,
    )
    # Analyst (grounding) có thể route sang model KHOẺ HƠN; rỗng → dùng planning_model.
    analyst_client = OpenAIChatCompletionClient(
        model=settings.planning_analyst_model or settings.planning_model,
        api_key=settings.openai_api_key or None,
        base_url=settings.openai_base_url or None,
    )

    # Grounding 2 tầng: keyword (deterministic, tức thì) làm BASE + FALLBACK, rồi
    # 1 lời gọi LLM 'analyst' HIỂU NGHĨA overlay lên trên. Analyst hỏng → giữ base.
    t_ground = time.perf_counter()
    base = _ground(req)
    facts = await _ground_semantic(analyst_client, req, base)
    context = _context(req, facts)
    logger.info(
        "planning: grounding done in %.1fs (%s) — shared context %d chars (sent x3)",
        time.perf_counter() - t_ground,
        "keyword-only" if facts is base else "semantic",
        len(context),
    )

    # Sinh 3 brief TUẦN TỰ — từng brief một, chờ xong cái này mới gọi cái kế.
    # Không bắn song song để KHÔNG oversubscribe gateway (~2 concurrent/key): tránh
    # starvation/timeout dây chuyền vốn làm planning chậm + degraded trong production.
    # Mỗi brief hỏng (timeout/treo) rơi về fallback deterministic riêng → request
    # luôn 200, plan vẫn dùng được; một brief hỏng KHÔNG ảnh hưởng các brief sau.
    specs = (
        (_INTERVIEW_BRIEF_SYS, "interview_brief"),
        (_EVALUATION_BRIEF_SYS, "evaluation_brief"),
        (_ASSIGNMENT_BRIEF_SYS, "assignment_brief"),
    )
    t_briefs = time.perf_counter()
    briefs: dict[str, str] = {}
    degraded: list[str] = []
    for system_prompt, label in specs:
        try:
            briefs[label] = await _gen_brief(client, system_prompt, context, label)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "planning: %s failed (%s) — using deterministic fallback",
                label, str(exc)[:160],
            )
            briefs[label] = _fallback_brief(label, req, facts)
            degraded.append(label)

    logger.info(
        "planning: ALL 3 briefs done SEQUENTIALLY in %.1fs total%s",
        time.perf_counter() - t_briefs,
        f" — {len(degraded)} fallback: {', '.join(degraded)}" if degraded else "",
    )

    # Directive máy-đọc của assignment_brief LẤY TỪ facts (deterministic), không tin
    # dòng LLM tự viết → type/mode/difficulty luôn khớp quyết định grounding.
    briefs["assignment_brief"] = _ensure_directive(briefs["assignment_brief"], facts)

    # Lưới quan sát nhất quán (chỉ log, không round-trip, không đổi nội dung).
    _verify_briefs(briefs, facts)

    return InterviewPlan(
        interview_brief=briefs["interview_brief"],
        evaluation_brief=briefs["evaluation_brief"],
        assignment_brief=briefs["assignment_brief"],
        duration_minutes=_duration_minutes(facts["seniority_level"]),
        source="planning-agent" if not degraded else "planning-agent+fallback",
    )
