import { User, JobPosition, RecruitmentCampaign, Candidate } from '@/types'

export const mockUser: User = {
  id: '1',
  email: 'admin@hrbot.com',
  name: 'John Doe',
  role: 'admin',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  createdAt: new Date().toISOString(),
}

export const mockJobPositions: JobPosition[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    description: 'We are looking for an experienced React developer to join our team.',
    requirements: ['5+ years of experience', 'React expertise', 'TypeScript proficiency'],
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
    seniority: 'senior',
    department: 'Engineering',
    salary: {
      min: 120000,
      max: 180000,
      currency: 'USD',
    },
    createdBy: mockUser.id,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Full Stack Developer',
    description: 'Join our team as a full-stack developer and build amazing products.',
    requirements: ['3+ years of experience', 'Full-stack skills', 'Agile experience'],
    skills: ['React', 'Node.js', 'MongoDB', 'Docker'],
    seniority: 'mid',
    department: 'Engineering',
    salary: {
      min: 80000,
      max: 130000,
      currency: 'USD',
    },
    createdBy: mockUser.id,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Junior Developer',
    description: 'Great opportunity for a junior developer to grow and learn.',
    requirements: ['0-2 years of experience', 'JavaScript knowledge', 'Eager to learn'],
    skills: ['JavaScript', 'HTML', 'CSS', 'React'],
    seniority: 'junior',
    department: 'Engineering',
    salary: {
      min: 50000,
      max: 80000,
      currency: 'USD',
    },
    createdBy: mockUser.id,
    createdAt: new Date().toISOString(),
  },
]

export const mockRecruitmentCampaigns: RecruitmentCampaign[] = [
  {
    id: '1',
    name: 'Senior React Developer - Q3 2024',
    jobPositionId: '1',
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    createdBy: mockUser.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Full Stack Developer - Q3 2024',
    jobPositionId: '2',
    startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    createdBy: mockUser.id,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Junior Developer - Q2 2024',
    jobPositionId: '3',
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'closed',
    createdBy: mockUser.id,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    phone: '+1-555-0101',
    cvUrl: 'https://example.com/cv/alice.pdf',
    stage: 'screening',
    score: 0.85,
    skills: ['React', 'TypeScript', 'Node.js'],
    education: ['Bachelor in Computer Science'],
    gpa: 3.8,
    experience: 6,
    campaignId: '1',
    appliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    firstName: 'Bob',
    lastName: 'Smith',
    email: 'bob.smith@example.com',
    phone: '+1-555-0102',
    cvUrl: 'https://example.com/cv/bob.pdf',
    stage: 'applied',
    score: 0.72,
    skills: ['React', 'JavaScript', 'CSS'],
    education: ['Bachelor in Information Technology'],
    gpa: 3.5,
    experience: 3,
    campaignId: '2',
    appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    firstName: 'Carol',
    lastName: 'Williams',
    email: 'carol.williams@example.com',
    phone: '+1-555-0103',
    cvUrl: 'https://example.com/cv/carol.pdf',
    stage: 'virtual_interview',
    score: 0.88,
    skills: ['TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
    education: ['Master in Computer Science'],
    gpa: 3.9,
    experience: 7,
    campaignId: '1',
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@example.com',
    phone: '+1-555-0104',
    cvUrl: 'https://example.com/cv/david.pdf',
    stage: 'rejected',
    score: 0.45,
    skills: ['JavaScript', 'HTML'],
    education: ['Bootcamp Certificate'],
    gpa: 2.8,
    experience: 1,
    campaignId: '2',
    appliedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    firstName: 'Emma',
    lastName: 'Davis',
    email: 'emma.davis@example.com',
    phone: '+1-555-0105',
    cvUrl: 'https://example.com/cv/emma.pdf',
    stage: 'hr_review',
    score: 0.92,
    skills: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'AWS'],
    education: ['Bachelor in Computer Science', 'AWS Certification'],
    gpa: 3.9,
    experience: 5,
    campaignId: '1',
    appliedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
